### PR TITLE
LPS-74362 User menus do not appear to non-admin users on virtual instances before restarting server

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-74362](https://issues.liferay.com/browse/LPS-74362).<br><br>Hey Pei-Jung, would you mind building this branch and testing it?  I had one weird instance where I built from scratch and nothing registered at all, so I need to make sure it wasn't an environment thing.

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by pei-jung** [comment]
Great job, Drew! 👍 

I made a few minor changes. Please see https://github.com/drewbrokke/liferay-portal/pull/378.

**Comment by brandizzi** [comment]
:clap: :clap: :clap:

**Pull request closed without merging**
