### PR TITLE
LPS-105477

### PR DESCRIPTION
**Pull request by brianikim**
Resending from https://github.com/pei-jung/liferay-portal/pull/543 to address test failures.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hi @brianikim, can you apply the same change to the finder so that we get the same behavior for both the index and db search. Also, please add a test for this. Thanks!

**Comment by brianikim** [comment]
Hello @pei-jung ,

I will take care of the requests.

Sincerely,
Brian Kim

**Pull request closed without merging**
