### PR TITLE
LPS-76024

### PR DESCRIPTION
**Pull request by noahsherrillwork**
@JorgeFerrer, @drewbrokke , @willnewbury

### CODE REVIEW

**Comment by noahsherrillwork** [comment]
ci:test

**Comment by noahsherrillwork** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
> Do we really need an extra level for the announcements-uad modules? Why not just have both announcement-uad and announcements-uad-test under announcements?

I agree. They should both be just be child modules of `announcements`.

**Comment by noahsherrillwork** [comment]
The requested changes have been made: pei-jung#227.

**Pull request closed without merging**
