### PR TITLE
LPS-78524 Make Properties tabs in Server Admin consistent with Lexicon design

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LPS-78524

@jonmak08

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
@jonmak08 test

**Comment by jonmak08** [comment]
@jonmak08 test

**Comment by jonmak08** [comment]
@jonmak08 test2

**Comment by alee8888** [comment]
@alee8888 comment test

**Comment by jonmak08** [comment]
LGTM.  Thanks @alee8888!

**Pull request closed without merging**
