### PR TITLE
LPS-190949  Can not view site calendar event as the guest

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@xbrianlee can you help me review the test results? Are the failures related?

**Comment by xbrianlee** [comment]
ci:test:calendar

Running this suite since it contains tests that caught this regression

**Comment by xbrianlee** [comment]
@pei-jung The test results look good. The [test that caught the regression](https://testray.liferay.com/home/-/testray/case_results/2390412281) is now passing. Can I forward this?

**Comment by pei-jung** [comment]
Yes, it's ready to forward. Thanks @xbrianlee!

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
