### PR TITLE
LPS-112726

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
Hi @pei-jung ,
I am not an UI expert, so I am not sure the solution of UI is right or not. I hope it's the right way.

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hey @yxingwu 

Sorry for the delay in reviewing this. I've requested a design from our designer. I'll keep you updated when I hear back.

**Comment by pei-jung** [comment]
New changes sent in https://github.com/brianchandotcom/liferay-portal/pull/92725.

**Pull request closed without merging**
