### PR TITLE
LPS-127860 URL in mail verification has 'nullnull' after creating a new virtual instance

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @IstvanD @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by Sharryxue** [comment]
The failed functional test notrelated the changes here, issue addressed in [LPS-128239](https://issues.liferay.com/browse/LPS-128239).

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez can you manually forward this to Brian? Thanks!

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/99116

**Pull request closed without merging**
