### PR TITLE
LPS-123954 WARN message Unable to add list type in console during the upgrade of com.liferay.portal.upgrade.v7_4_x.UpgradeListType

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez is this failure unrelated?

**Comment by pei-jung** [comment]
I'll fix the SF failure after the upgrade tests finish.

**Comment by patriciajeanperez** [comment]
@drewbrokke looks like it timed out. will retest when Pei sends a new pull.

**Comment by Sharryxue** [comment]
No specific issue found in **ci:test:upgrade** job.
[PostgreSQL 11](https://testray.liferay.com/zh/home/-/testray/case_results?testrayTeamId=1310700616&testrayBuildId=1359886991&testrayRunId=1359935909), same issue as in [LPS-124277](https://issues.liferay.com/browse/LPS-124277)
[Oracle Database 19.3](https://testray.liferay.com/zh/home/-/testray/case_results?testrayTeamId=1310700616&testrayBuildId=1359886991&testrayRunId=1359939292) same issue as in [LPS-124277](https://issues.liferay.com/browse/LPS-124277)
[IBM DB2 11.1](https://testray.liferay.com/zh/home/-/testray/case_results?testrayTeamId=1310700616&testrayBuildId=1359886991&testrayRunId=1359926878), same issue as in [LPS-124277](https://issues.liferay.com/browse/LPS-124277)
[Microsoft SQL Server 2017](https://testray.liferay.com/zh/home/-/testray/case_results?testrayTeamId=1310700616&testrayBuildId=1359886991&testrayRunId=1359938431), same issue as in [LPS-124277](https://issues.liferay.com/browse/LPS-124277)
[MySQL 5.7](https://testray.liferay.com/zh/home/-/testray/case_results?testrayTeamId=1310700616&testrayBuildId=1359886991&testrayRunId=1359887068) and [MariaDB 10.2](https://testray.liferay.com/zh/home/-/testray/case_results?testrayTeamId=1310700616&testrayBuildId=1359886991&testrayRunId=1359895558) same issue as in [LPS-124517](https://issues.liferay.com/browse/LPS-124517) and [LPS-124495](https://issues.liferay.com/browse/LPS-124495)
/cc @patriciajeanperez @pei-jung

**Comment by patriciajeanperez** [comment]
will retest once https://github.com/brianchandotcom/liferay-portal/pull/96768 is merged

**Comment by patriciajeanperez** [comment]
ci:test:upgrade

**Comment by pei-jung** [comment]
ci:stop

**Comment by pei-jung** [comment]
I need to fix the SF failure first. Will resend the PR and re-trigger the upgrade tests.

**Comment by pei-jung** [comment]
Resent as https://github.com/pei-jung/liferay-portal/pull/747

**Pull request closed without merging**
