### PR TITLE
LPS-123628 As an administrator, I want to pre-populate countries and regions used by both Portal and Commerce

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:reevaluate:1067401_8223

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@patriciajeanperez are the failures related to the changes in the PR?

**Comment by pei-jung** [comment]
ci:reevaluate:1027401_269

**Comment by pei-jung** [comment]
ci:forward

**Comment by Sharryxue** [comment]
No related upgrade failure found.
- DB2 upgrade failure addressed [LPS-127996](https://issues.liferay.com/browse/LPS-127996), not related
- sqlserver2017 upgrade failure addressed [LPS-119128](https://issues.liferay.com/browse/LPS-119128), not related
- [com.liferay.portal.upgrade.test.UpgradeRegistryTest](https://testray.liferay.com/zh/home/-/testray/case_results/1518476538) failure addressed [LPS-129558](https://issues.liferay.com/browse/LPS-129558), not related

**Pull request closed without merging**
