### PR TITLE
[TECHNICAL-SUPPORT] LPS-83375

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
@pei-jung I didn't apply the second change elsewhere since I couldn't reproduce any strange behavior for those menus.

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61343. Thanks!

**Pull request closed without merging**
