### PR TITLE
LPS-55590 User service to declare it under the right interface

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @pei-jung 

Sorry for the delay reviewing the pull.

I have done some changes in your code. Please, review them carefully and let me know if you have any question about them.

I did 2 changes and I'm not entirely sure if they're right or not: https://github.com/sergiogonzalez/liferay-portal/commit/7cdd9bd423f9005c2956a54b0568dc901946ca47 and https://github.com/sergiogonzalez/liferay-portal/commit/7f055a215c05e0b01f6e05e9052617de0fd1300b

Please, make sure to test everything and review the code carefully.

Thanks,
Sergio

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @pei-jung 
I'm not sure about that since I'm not familiar with that logic. Maybe you can ask Jorge?

**Comment by pei-jung** [comment]
Hey @sergiogonzalez,

Sure, I'll check with Jorge. Thank you for taking the time to review my code! :)

**Comment by sergiogonzalez** [comment]
@pei-jung no problem :+1:

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/JorgeFerrer/liferay-portal/pull/556.

**Pull request closed without merging**
