### PR TITLE
LPS-119458

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @holatuwol @hongvo2308 @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failure is more like fluky, will retriger the forward test.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
