### PR TITLE
LPS-121997 Update service.xml and add Upgrade processes for Country

### PR DESCRIPTION
**Pull request by alee8888**
@pei-jung @drewbrokke

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@alee8888 I think you need to run `build-upgrade-table` again. I just ran it locally rebased off of this branch and there were changes to the `CountryTable` class.

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
