### PR TITLE
[TECHNICAL-SUPPORT] LPS-75045

### PR DESCRIPTION
**Pull request by jonathanmccann**
@pei-jung Sending this through you because Preston is unable to review it at this time (https://github.com/Preston-Crary/liferay-portal/pull/555). Please let me know if you'd like someone else to review it.

/cc @wanderlast

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
ci:test:relevant ci:test:sf

**Comment by wanderlast** [comment]
Closing. Resent here per reviewer's request: https://github.com/Preston-Crary/liferay-portal/pull/581

**Comment by wanderlast** [comment]
ci:close

**Pull request closed without merging**
