### PR TITLE
LPS-111581 Avoid exception in AccountEntryUserRelLocalServiceImpl.addAccountEntryUserRel

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-111581](https://issues.liferay.com/browse/LPS-111581).<br><br>Hi Pei-Jung, overall it looks great. I made one test refactoring change to unify the duplicated logic between the two similar test cases. If it looks good to you then we can forward to Brian.<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/87369

**Pull request closed without merging**
