### PR TITLE
LPS-121991 Upgrade portal Address with new fields

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-121991](https://issues.liferay.com/browse/LPS-121991).

@pei-jung I went ahead and updated the branch with my suggestion from https://github.com/drewbrokke/liferay-portal/pull/1196/commits/975bb8b06218c7ef6063b656a81d5edacd82f2c1?file-filters%5B%5D=.sql#r506523195. The `Role` and `Group` indexes were not added. Seems like it was a fluke, but unfortunately it means that we'll have to start inspecting our regen commits! 

/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez are these smoke test failures real?

**Comment by patriciajeanperez** [comment]
yes @drewbrokke, they are the same errors Sharry posted in a [previous pull](https://github.com/drewbrokke/liferay-portal/pull/1194#issuecomment-708897469) for this LPS. cc @pei-jung

**Comment by pei-jung** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1197.

**Pull request closed without merging**
