### PR TITLE
LPS-122718 Update icon for Antivirus configuration category

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez is this a fluke?

**Comment by patriciajeanperez** [comment]
Yes @pei-jung, it's a startup race condition. I will manually forward.

**Comment by patriciajeanperez** [comment]
Pushed to https://github.com/brianchandotcom/liferay-portal/pull/95381

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
