### PR TITLE
[TS]  LPS-129270

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-129039
https://issues.liferay.com/browse/PTR-2312

Please let me know if you have any questions, thanks!

CC @laszlopap

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by GezaGroma** [comment]
Hi guys,
Any news on this?
Thanks.

**Comment by ChrisKian** [comment]
Hi @GezaGroma,
Pei has been forwarding a lot of PRs recently, so she may be getting to this one soon, or she may have needed to switch back to development work.  If she hasn't made any progress at the 1-week mark, I'll reach out to her.

In the meantime, this solution should be safe for an SDH, since it can be reverted without any lasting effects.

Please let me know if you have nay other questions, thanks!

**Comment by GezaGroma** [comment]
Hi @ChrisKian,
Thanks a lot!

**Comment by pei-jung** [comment]
Sorry for the delay. Please see https://github.com/laszlopap/liferay-portal/pull/17 for additional changes to fix the language selector. Thanks!

**Pull request closed without merging**
