### PR TITLE
LPS-125991 Rename

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:commerce

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:reevaluate:1227401_7834

**Comment by pei-jung** [comment]
ci:reevaluate:1227401_7834

**Comment by pei-jung** [comment]
ci:reevaluate:1227401_7834

**Comment by pei-jung** [comment]
@patriciajeanperez looks like ci:reevaluate is not working. Can I re-trigger the relevant tests?

**Comment by jpince** [comment]
@pei-jung it'll be another 2-3 hours before the latest upstream acceptance run is done. I recommend re-running relevant.

Found this because I was mentioned [on Slack](https://liferay.slack.com/archives/CS52K673L/p1614351108031000).

**Comment by pei-jung** [comment]
I see. I'll re-run the tests then. Thanks @jpince!

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
