### PR TITLE
LPS-70161 Timezone label shows with the wrong locale

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-70161](https://issues.liferay.com/browse/LPS-70161).

@daledotshan @hhuijser

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:reopen

**Comment by daviddotzhang** [comment]
@drewbrokke @pei-jung ,

as this one is closed, could you reopen it ?

**Comment by pei-jung** [comment]
Hey @daviddotzhang,

Drew has sent the change to Brian. Please see https://github.com/brianchandotcom/liferay-portal/pull/46366. Thanks!

**Comment by drewbrokke** [comment]
Thanks for the clarification @pei-jung.  Sorry I did not comment about this on the pull, @daviddotzhang.

**Comment by daviddotzhang** [comment]
@pei-jung I saw only one commit was sent to brianchan, are the bellow necessary ?
 @drewbrokke	LPS-70161 refactor - util-taglib - page.jsp - replace logic in jsp wi
 @drewbrokke	LPS-70161 SF - removes unused attribute from request			3f877e1
 @drewbrokke	LPS-70161 portal-web - init.jsp - auto SF			bbd57ae
 @drewbrokke	LPS-70161 util-taglib - InputTimeZoneTag - refactor - use functional …  …

**Comment by drewbrokke** [comment]
Hey @daviddotzhang, they are not essential to the fix, and in the end I just send your fix through without these.

The idea for the refactor is that as a general rule, we should place as little logic in our JSP's as possible. Once a large script block shows up in our templates, we should consider moving it to a class.  It ended up being fairly complex so I opted to deal with the re-factoring later (I think we're going to migrate taglibs to Soy taglibs at some point).

Thanks for double-checking :) 👍

**Pull request closed without merging**
