### PR TITLE
[TECHNICAL-SUPPORT] LPS-104337

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @pei-jung,

I thought this would be a simple solution for the issue at hand that could be easily backported. I'm not sure if it would be useful to have a separate `name` and `key` value (much like Roles) but I think that would be best suited for a future release since it would require changes to the database.

Let me know what you think of the changes and if you have any concerns.

Thanks.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@pei-jung Have you had a chance to review these changes yet?

**Comment by pei-jung** [comment]
Hi @jonathanmccann,

Sorry for the delay in reviewing this. Overall, I'm fine with removing the `key` column in the table since there's not actual distinction between the `key` and `name` fields. However, I'm not sure about not localizing the custom field names. If there's are customers trying to localize the custom fields names, this change can cause regression. I'll check with our product manager to see what should be the expected behavior.

Also, if we decide not to localize the names, we'll need to update the expando taglib too. https://github.com/liferay/liferay-portal/blob/master/modules/apps/expando/expando-taglib/src/main/resources/META-INF/resources/custom_attribute/page.jsp#L63

**Comment by jonathanmccann** [comment]
@pei-jung Thank you for the response. Did you happen to speak with the PM?

**Comment by pei-jung** [comment]
Hi @jonathanmccann, not yet. I was out last Wednesday to Friday, and our PM was at DevCon last week. I'll talk to him about this today.

**Comment by pei-jung** [comment]
Hi @jonathanmccann 

After talking to Dennis, we decided to add a new property to control whether to translate the label or not. Please add the following changes and resend.

- Add a new property `PROPERTY_LOCALIZE_LABEL` in `ExpandoColumnConstants`
- Add a new toggle "Localize Label" under ADVANCED PROPERTIES with a help text and default to true to preserve the old behavior and avoid regression

Screen Shot 2019-11-25 at 4 52 54 PM

- Update the view attributes table to display the name based on the new property in `expando-web/src/main/resources/META-INF/resources/attribute_columns.jspf`
- Update the expando taglib to reflect the new property. Use the [localizeLabel](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/META-INF/liferay-aui.tld#L396-L402) for the <aui:field-wrapper> in https://github.com/liferay/liferay-portal/blob/master/modules/apps/expando/expando-taglib/src/main/resources/META-INF/resources/custom_attribute/page.jsp#L63

Since the properties are saved in ExpandoColumn's `typeSettings`, this change doesn't need an upgrade and should be easy to backport. Let me know if you have any questions. Thanks!

/cc @dejuknow @drewbrokke

**Comment by jonathanmccann** [comment]
@pei-jung Thank you for the detailed reply. I have two questions about the above:

1. It might be confusing for users who leave the "Localize Label" as true but then the label isn't localized because the text they inputted for the label is not in `language.properties`. Is this an acceptable flaw and in order for all text to be localizable they will need to override our language keys?

2. In the case that the user toggles "Localize Label" to false there is still the issue of having two columns (name and key) that are exactly the same. Do you still want to display both columns?

**Comment by pei-jung** [comment]
1. We're aware of the flaw of the decision. If the user wants the custom fields to be properly translated, s/he will need to make sure the corresponding language keys exist in the language files. Unfortunately, there's no simple solution for that at the moment. If we want to avoid adding translations via language.properties, another way will be to add a localized field, similar to the Role title field. However, the value added might not worth the effort. I think if we explain the limitation clearly in the help text, that should be fine. We can also move the toggle/checkbox right below the name field so it pops out to the user.

    @dejuknow can we ask David for a quick design for the new toggle?

2. We can remove the `key` column in the table since they are the same.

**Comment by dejuknow** [comment]
@pei-jung @jonathanmccann 

Let's leave the new toggle under "Advanced Properties" (as opposed to moving it below the Field Name).

Adding localized field is ideal, but as you stated, it would require quite some work, especially because our multi-option custom fields (like radio, checkbox, etc) are using a multi-line text area.

3. For the toggle design, let's do the following:
3a. Position: first toggle in "Advanced Properties" (above "Visible with Update")
3b. Toggle name: "Localizable Field Name" (or should we go with "Localizable Field Label"?. I like the former since the name field is named "Field Name" (that was a confusing sentence. lol).
3c. Toggle description: "Setting a custom field to localizable field name means that the field's name will be localized according to the language keys defined in the language properties file. Refer to documentation to override the default language keys."

**Comment by jonathanmccann** [comment]
https://github.com/pei-jung/liferay-portal/pull/542

**Pull request closed without merging**
