### PR TITLE
LPS-112588 Change Account Manager to organization role

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:accounts

**Comment by pei-jung** [comment]
@patriciajeanperez I need your help with the failed tests. They look unrelated to me. Can you confirm? Thanks.

`    [javac] /opt/dev/projects/github/liferay-portal/util-java/src/com/liferay/util/xml/descriptor/SimpleXMLDescriptor.java:1: error: illegal character: '\u0000'
`

**Comment by patriciajeanperez** [comment]
Hi @pei-jung! Yes they seem unrelated

**Comment by pei-jung** [comment]
Thanks for confirming @patriciajeanperez!

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
