### PR TITLE
LPS-90260 Create hidden pages for user apps belonging to the current site's theme

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70763. Thanks!

**Pull request closed without merging**
