### PR TITLE
LPS-111509 Rename default account roles and add descriptions

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-111509](https://issues.liferay.com/browse/LPS-111509).<br><br>Hey Pei, I made a couple of code style changes, but otherwise this is good. Please look over my changes, and if they look good, go ahead and forward to Brian. Thanks!<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez I force-pushed some changes so you may want to re-run the accounts suite.

**Comment by patriciajeanperez** [comment]
oh, good thing that was a typo. should have been accounts @drewbrokke will rerun. Thanks!

**Comment by patriciajeanperez** [comment]
ci:test:accounts

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@patriciajeanperez can you help look into the test failures? Where do the failures occur?

**Comment by patriciajeanperez** [comment]
@pei-jung looks like the same issue as https://issues.liferay.com/browse/LPS-108899. Looking into why it's consistent in this pull

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Hi @pei-jung, the PR is failing from this error

`23:28:46,809 ERROR [main][UpgradeStepRegistratorTracker:144] Failed upgrade process for module com.liferay.account.service
com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '20097-Account Manager' for key 'IX_EBC931B8'`

Here is the [link](https://testray.liferay.com/reports/production/logs/test-1-6/1587418984240/test-portal-acceptance-pullrequest%28master%29/6121/functional-upgrade-tomcat90-mysql57-jdk8_stable/10/0/liferay-log.txt.gz) to the full app server log.

**Comment by pei-jung** [comment]
fixed the upgrade error and re-testing here https://github.com/pei-jung/liferay-portal/pull/610

**Pull request closed without merging**
