### PR TITLE
LPS-123954 WARN message Unable to add list type in console during the upgrade of com.liferay.portal.upgrade.v7_4_x.UpgradeListType

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by pei-jung** [comment]
@patriciajeanperez are these test failures related to my changes?

**Comment by patriciajeanperez** [comment]
Hi @pei-jung, I didn't see any unique failures. Is this ready to be forwarded?

**Comment by pei-jung** [comment]
@patriciajeanperez yes, the changes are ready to send if there's no more upgrade errors relating to list types.

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by pei-jung** [comment]
thanks @patriciajeanperez!

**Pull request closed without merging**
