### PR TITLE
LPS-109035 Assign users to account role

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez looks like the test failures are unrelated. Can you confirm? thanks!

**Comment by patriciajeanperez** [comment]
Intermittent failure according to LPS-105888.

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
