### PR TITLE
LPS-115749 Add AccoutGroupsAccountEntryRel

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez is this a real test failure? can I re-run?

**Comment by patriciajeanperez** [comment]
looks like LRCI-1431. I can retrigger @pei-jung

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
