### PR TITLE
COMMERCE-5768 Countries and Regions are not selectable when adding a new address

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @alecsloan @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:reevaluate:1067401_8117

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:reevaluate:1027401_217

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/99874

**Pull request closed without merging**
