### PR TITLE
LPS-92344 Default User is displayed in User Administration Web

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-92344](https://issues.liferay.com/browse/LPS-92344).<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian @arboliveira @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@pei-jung please see my comments here: https://issues.liferay.com/browse/LPS-92344?focusedCommentId=1782585&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1782585

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71939. Thanks!

**Pull request closed without merging**
