### PR TITLE
LPS-77801 Unable to delete assigned User Groups, Organizations and Sites in Roles assignment

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-77801](https://issues.liferay.com/browse/LPS-77801).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
Hey @pei-jung is there anything you need me to do for this ticket?

**Comment by pei-jung** [comment]
Sorry for the delay. I totally forgot about this PR.

Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55617. Thanks!

**Comment by drewbrokke** [comment]
Haha, no worries.  Thanks @pei-jung!

**Pull request closed without merging**
