### PR TITLE
LPS-111508 As an account manager, I want to enter an account's tax ID number (VAT, EIN, etc)

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-111508](https://issues.liferay.com/browse/LPS-111508).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
@pei-jung will you please look over these changes? I added some additional commits at the end that are unrelated but improve the code structure of `accounts-admin-web` IMO. If it looks good to you then go ahead and forward to Brian. Thanks!

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
LGTM. I added a minor change, see https://github.com/pei-jung/liferay-portal/pull/626. Thanks!

**Pull request closed without merging**
