### PR TITLE
[TECHNICAL-SUPPORT] LPS-91021

### PR DESCRIPTION
**Pull request by jonathanmccann**
Resent from https://github.com/pei-jung/liferay-portal/pull/345#issue-256320590

Please let me know your thoughts on this one. This way makes the most sense to me but I might be missing something.

The issue is that we need to maintain the authentication portion due to LPS-44538 but authenticating will fail since the user's password is expired.

Thanks.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@pei-jung Have you had a chance to look at this pull request?

**Comment by pei-jung** [comment]
@jonathanmccann not yet. Sorry for the delay. I'm overloaded while Drew is on paternity. I'll try to take a look at it today.

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/69542

**Pull request closed without merging**
