### PR TITLE
LPS-113948 Add Search for Account Groups

### PR DESCRIPTION
**Pull request by alee8888**
@drewbrokke

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:forward

**Comment by Sharryxue** [comment]
The failed test not specific for this pull, addressed the issue in [LRQA-58148](https://issues.liferay.com/browse/LRQA-58148?focusedCommentId=2180445&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2180445), also contact the arthur(Lawrence) for help.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
