### PR TITLE
LPS-113948 Add Search for Account Groups

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez I didn't get any service builder changes locally. Is the test failure a fluke?

**Comment by patriciajeanperez** [comment]
looks like it timed out, i will rerun ci:forward for you @pei-jung

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by pei-jung** [comment]
thanks @patriciajeanperez!

**Comment by patriciajeanperez** [comment]
Hi @hhuijser, can you please take a look at the SF errors that were caused by https://github.com/liferay/liferay-portal/commit/27ec0db899c9a750e1283a9ed11acb0ad221b6d8#diff-60845a99f2f4c6b71a6f0add0fd0b320? Thank you!

**Comment by pei-jung** [comment]
I rebuilt service builder and regen the service. I believe that should fix the issue. Will rerun the tests.

**Comment by pei-jung** [comment]
ci:forward

**Comment by alee8888** [comment]
reset here: https://github.com/pei-jung/liferay-portal/pull/641

**Pull request closed without merging**
