### PR TITLE
LPS-119953 Organization types do not persist after ugprade



### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888 @patriciajeanperez @Sharryxue

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez @Sharryxue should I wait till LPS-120338 is fixed before re-triggering the tests?

**Comment by patriciajeanperez** [comment]
Hi @pei-jung! no, I can manually send to Brian. Thanks!

**Comment by patriciajeanperez** [comment]
ci:test:upgrade

**Comment by pei-jung** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/93771

**Pull request closed without merging**
