### PR TITLE
LPS-129586 Migrate selection modals in account modules

### PR DESCRIPTION
**Pull request by markocikos**
Hey @pei-jung ,

I was told to redirect to you from https://github.com/drewbrokke/liferay-portal/pull/1331

JIRA ticket: https://issues.liferay.com/browse/LPS-129586

This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/933

In this PR, we are:
1. Cleaning up unnecessary `selectEntityHandler`s, after previous migration of modals to `openSelectionModal`
2. Improving `openSelectionModal` to support multiple selection in search container. More specifically, we are setting selected items to callback in the utility, instead of needing to do this in JSPs. To use this feature, we need to set `openSelectionModal` params `searchContainerId` and `multiple = true`.

Test cases:
GM > Accounts > An account > Users > (+) 
GM > Accounts > An account > Details > Set Default Address
GM > Account Users > A user > General > Accounts > Select
GM > Account Groups > A group > (+)
GM > Accounts > An account > Organizations > (+)
GM > Account Users > Filter and Order > Accounts

All features of modals should be preserved after this PR.

/cc @jbalsas @kresimir-coko @jonmak08

after

### CODE REVIEW

**Comment by markocikos** [comment]
Force-pushed!

I found two more cases of setting selected item data in account modules, so I removed them as well. I updated opening comment with two new test cases.

One of those had a regression bug from our management toolbar migration: we set a filter dropdown item as an action dropdown item. Fixed in https://github.com/pei-jung/liferay-portal/pull/815/commits/4548646403e51d73dfd6780b6a7e256b15903ebf

/cc @jonmak08

This is the fixed regression:
after

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Test cases:

- [ ] GM > Accounts > An account > Users > (+)
- [ ] GM > Accounts > An account > Details > Set Default Address
- [ ] GM > Account Users > A user > General > Accounts > Select
- [ ] GM > Account Groups > A group > (+)
- [ ] GM > Accounts > An account > Organizations > (+)
- [ ] GM > Account Users > Filter and Order > Accounts

**Comment by drewbrokke** [comment]
@markocikos everything seems to be functioning correctly. Lots of removals, I like this! :)

@pei-jung LGTM, I'm ready to forward whenever you are.

**Review by drewbrokke — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
