### PR TITLE
LPS-69535 & LPS-69542 (Changes related to Roles only)

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @pei-jung,

This is part of a larger set of fixes to improve the performance of loading a portlet's Permissions window when there are a large amount of roles. The full set of fixes contains modifications to edit_permissions.jsp which call the finder methods created here, but Julio asked me to break it up into two pull requests - one to the Roles team and one to the Portlet Configuration team. You can view the full fix at https://github.com/juliocamarero/liferay-portal/pull/4331.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by pei-jung** [comment]
Hi @mbowerman,

Can you try to do this with DynamicQuery instead? We want to avoid using custom sql and use DynamicQuery if possible. By using DynamicQuery, we can have the queries built directly in the services class without creating finder implementations. The code is cleaner and easier to maintain that way.

Here is the doc on [DynamicQuery](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/dynamic-query). Let me know if you run into any issues or have any questions. Thanks!

/cc @drewbrokke

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/drewbrokke/liferay-portal/pull/265. Thanks!

**Pull request closed without merging**
