### PR TITLE
LPS-76504 Admin user lost permissions when use a new password policy

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-76504](https://issues.liferay.com/browse/LPS-76504).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by pei-jung** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:retest

**Comment by pei-jung** [comment]
Please add a test for this and send it to Brian. Thanks!

**Pull request closed without merging**
