### PR TITLE
LPS-90259 Create hidden pages for user apps belonging with Dashboard theme

### PR DESCRIPTION
**Pull request by stsquared99**
/cc @drewbrokke @alee8888 @ChrisKian

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
@pei-jung One of the failures is related to my logic in the PCI's, I'll fix that, but the rest I'm not seeing how they are related yet

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70423. Thanks!

**Pull request closed without merging**
