### PR TITLE
[TS] LPS-124190 Add weak reference to roleGroups

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @pei-jung ,

I'm forwarding this PR to you: https://github.com/vendeltoreki/liferay-portal/pull/153 . From staging perspective, it looks OK.

Please review the changes.

cc: @balazssk 

Thanks,
Vendel

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:stable

**Comment by Sharryxue** [comment]
Trigger the re;avant job before reviewing.

**Comment by balazssk** [comment]
Hi @pei-jung , @Sharryxue 
Can you please share any update on this PR?
Thanks.
Balázs

**Comment by pei-jung** [comment]
Hi @balazssk, if possible, can you add a test for this? Thanks!

**Comment by vendeltoreki** [comment]
Hi @pei-jung ,

We've created [LRQA-63791](https://issues.liferay.com/browse/LRQA-63791) ticket for adding a new functional test case to cover this scenario.

I think the PR can be committed to master if the change looks ok, so the test can be added afterwards.

Thanks,
Vendel

**Comment by pei-jung** [comment]
@vendeltoreki that works too! Just want to make sure we have test coverage for this to prevent future regression. I'll forward this for the time being.

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:help

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
