### PR TITLE
LPS-119613 Changes to email address and screen name do not save

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by Sharryxue** [comment]
No failure are specific to this pull.
The _semantic-versioning-jdk8_ issue is in commen with master upstream, and already reported to BChan. Refer [slack](https://liferay.slack.com/archives/C011FUR3QP5/p1598924677000400).
The _lpkg-controller-jdk8/null_ and _lpkg-base-jdk8_ issue is addressed in LPS-120169 and bring up in team channel.

**Comment by pei-jung** [comment]
Hey @patriciajeanperez, should I wait till the issue that Sharry mentioned above to get resolved first before re-trigger the tests?

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:stop

**Comment by patriciajeanperez** [comment]
Hi @pei-jung, we could run the ci:forward since Jason pushed in a revert causing those batches to fail, but I will manually forward to save time and resources since Sharry already tested this PR.

**Comment by pei-jung** [comment]
sounds good. thanks @ patriciajeanperez!

**Pull request closed without merging**
