### PR TITLE
LPS-97290 Allow view notifications portlet when user has no access to the private pages of the site

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by pei-jung** [comment]
Hi @jkappler @pavel-savinov,

I might be missing something, but I still get the same error after deploying the change. Can you double check the fix?

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@pei-jung, seems that this happens only the first time with the fix. Afterwards it works as intended, and that's why we might have overlooked it

cc:// @pavel-savinov

**Comment by pei-jung** [comment]
Ah ok. Can you fix it and resend? I'll close the pull for now. Thanks!

**Pull request closed without merging**
