### PR TITLE
LPS-123954 WARN message Unable to add list type in console during the upgrade of com.liferay.portal.upgrade.v7_4_x.UpgradeListType

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888 @patriciajeanperez @Sharryxue

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by Sharryxue** [comment]
Hello @pei-jung,
There are some upgrade tests faied for `Unable to add list type`  seems related to the changes, it affect both of _Microsoft SQL Server 2017_ and _PostgreSQL 11_, refer [full console](https://testray.liferay.com/reports/production/logs/test-1-1/1607569962423/test-portal-acceptance-pullrequest(master)/6237/functional-upgrade-tomcat90-sqlserver2017-jdk8/1/23/jenkins-console.txt.gz), [testray](https://testray.liferay.com/zh/home/-/testray/case_results/1368411087), error as below, would you please dounble check? Thanks in advance.
```
 [parallel] 06:59:50,977 INFO  [main][UpgradeProcess:101] Upgrading com.liferay.portal.upgrade.v7_4_x.UpgradeListType
 [parallel] 06:59:50,987 WARN  [main][UpgradeListType:72] Unable to add list type
 [parallel] com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'dual'.
 [parallel] 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
 [parallel] 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624)
 [parallel] 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594)
 [parallel] 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
 [parallel] 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
 [parallel] 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
 [parallel] 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
 [parallel] 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
 [parallel] 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:473)
 [parallel] 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
 [parallel] 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
 [parallel] 	at com.liferay.portal.upgrade.v7_4_x.UpgradeListType._addListType(UpgradeListType.java:68)
 [parallel] 	at com.liferay.portal.upgrade.v7_4_x.UpgradeListType.doUpgrade(UpgradeListType.java:37)
 [parallel] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:104)
 [parallel] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:131)
 [parallel] 	at com.liferay.portal.upgrade.PortalUpgradeProcess.doUpgrade(PortalUpgradeProcess.java:130)
 [parallel] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:104)
 [parallel] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:156)
 [parallel] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:119)
 [parallel] 	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:182)
 [parallel] 	at com.liferay.portal.tools.DBUpgrader._upgradePortal(DBUpgrader.java:334)
 [parallel] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:151)
 [parallel] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:364)
 [parallel] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4678)
 [parallel] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5139)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
 [parallel] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
 [parallel] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
 [parallel] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1830)
 [parallel] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 [parallel] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 [parallel] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
 [parallel] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
 [parallel] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
 [parallel] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
 [parallel] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
 [parallel] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
 [parallel] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
 [parallel] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 [parallel] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
 [parallel] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
 [parallel] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
 [parallel] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:738)
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 [parallel] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 [parallel] 	at java.lang.reflect.Method.invoke(Method.java:498)
 [parallel] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
 [parallel] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
 [parallel] 06:59:50,989 INFO  [main][UpgradeProcess:115] Completed upgrade process com.liferay.portal.upgrade.v7_4_x.UpgradeListType in 12 ms
```

**Comment by pei-jung** [comment]
Thanks @Sharryxue! I'll look into it.

**Pull request closed without merging**
