### PR TITLE
LPS-85390 Documents fail to export if binary is missing/inaccessible

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by Sharryxue** [comment]
The Sematic version issue is fixed in upstream, and the upgrade one seems fluke, will retrigger the relevant test.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
