### PR TITLE
LPS-72690 Shopping service module should not use ServiceReference annotation to point to itself

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-72690](https://issues.liferay.com/browse/LPS-72690).

Hey @Pei-Jung, I was asked by Hugo to fix the SF errors in the shopping-service module. Here's the change to SF that brought this about: https://issues.liferay.com/browse/LPS-72562, and the request from Hugo: https://github.com/brianchandotcom/liferay-portal/pull/48971/#issuecomment-301357207.  

This raises an important point though.  We should make sure that any components we define inside a service module do *not* have the same package prefix as the service package prefix defined in the `bnd.bnd`.  That is the reason this SF error is triggering in the first place, even though there is actually no issuse with using the `@ServiceReference` annotation this way.  The recommendation from SF to use a `@BeanDeclaration` reference instead (the SB entity references defined at the bottom of each entity inside `service.xml` files) cannot apply in this case, since the referenced services are not SB entities, but merely OSGi components.

You can see a case of this being done correctly in `KBArticleLocalServiceImpl.java`, where a `@ServiceReference` is used to get a component that is also part of the `knowledge-base-service` module (`KBArticleImporter`), but the referenced class file does _not_ have the same package prefix as the one defined in the `bnd.bnd`, so it does not trip the SF.

Unfortunately, we can't just change the package path of those components without triggering a big semver update (since their package is being exported).  We got a little lucky though, since only static methods are being used on those components, so we don't need to get them through OSGi.

Let me know if you have any questions.

/cc @hhuijser, @brianchandotcom, @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
Ugh, looks like we're going to face semver either way.  @hhuijser is there a way we can take into account the fact that the annotated fields are not themselves SB entities?

**Comment by pei-jung** [comment]
Hey @drewbrokke,

We use `@ServiceReference` to reference spring beans. Since ShoppingItemPermission and ShoppingCategoryPermission are available as osgi service, I believe we can just use the `@Reference` annotation to get the service.

**Comment by pei-jung** [comment]
Sorry, I got confused with the usage of `@SeriveReference`. I've modified my comment. Please ignore what I wrote earlier.

**Comment by hhuijser** [comment]
Hey @drewbrokke I'll look into this more later

**Comment by hhuijser** [comment]
@drewbrokke, what about we exclude those from SF by keeping the exlusion file?
For any future cases we'll force them to have different package paths.

**Comment by drewbrokke** [comment]
@hhuijser that's fine by me.  We'll go ahead and close this one as won't fix.

cc @pei-jung

**Pull request closed without merging**
