### PR TITLE
LPS-90257 Add dropdown menu to the User Personal Bar

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @stsquared99 @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
- [ ] Remove 'getPortlet()' the base class
- [ ] Update the component registration properties to remove 'user'
- [ ] Can we get away without manually creating an Aggregate resource bundle?
- [ ] Inline PersonalMenuDropdownItemsProvider into the Resource command
- [ ] remove left over 'index' variable in PersonalMenuDropdownItemsProvider
- [ ] product-navigation-user-personal-bar-web view.jsp - is there any chance of code injection from the use of the label attribute of the personal-menu taglib?

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Pull request closed without merging**
