### PR TITLE
LPS-105477

### PR DESCRIPTION
**Pull request by brianikim**
Resent from https://github.com/pei-jung/liferay-portal/pull/544

https://issues.liferay.com/browse/LPS-105477

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Test results look good @pei-jung

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83369. Thanks!

**Pull request closed without merging**
