### PR TITLE
LPS-97249 Virtual Instances host name validation is inconsistent when editing

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LPS-97249

@jonmak08

### CODE REVIEW

**Comment by alee8888** [comment]
cs:test:sf

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75959. Thanks!

**Pull request closed without merging**
