### PR TITLE
LPS-108187 As an admin, I want to assign the account manager role to organization users so that they can manage accounts associated to that organization

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-108187](https://issues.liferay.com/browse/LPS-108187).<br><br>Hey Pei, I think I was able to successfully modularize the changes. Will you please look over them and make sure that everything looks good to you and works properly? Let me know if you'd  like to go over it with me.<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@pei-jung I just pushed a fix for an unrelated test failure. It should prevent this pull from failing CI, though I guess you'll probably forward from a different branch so you can clean up the history. If it's not merged yet, please include the commit for LPS-113274 so that your pull can pass CI also.

**Comment by pei-jung** [comment]
See https://github.com/pei-jung/liferay-portal/pull/619

**Pull request closed without merging**
