### PR TITLE
LPS-100991 Provide full support for LocalizedValueMap in OSGi configurations

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-100991](https://issues.liferay.com/browse/LPS-100991).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
LGTM. Do you want me to forward this to Brian?

**Comment by drewbrokke** [comment]
Thanks Pei. I'll do it. That way I'll just take care of any issues so you don't have to field them.

**Comment by pei-jung** [comment]
Sounds good. Thanks!

**Pull request closed without merging**
