### PR TITLE
LPS-176905 As an Admin, I'd like to manage service accounts in the UI

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Test failures are known flaky issues tracked in https://issues.liferay.com/browse/LRQA-73764. This is good to go.

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
