### PR TITLE
LPS-129423 Remove the Hello World widget

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:reevaluate:1217401_7834

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@patriciajeanperez  are these failures related?

**Comment by patriciajeanperez** [comment]
Hey @pei-jung, yes they are tests that need to be updated. I will send the test fixes with this pull to Brian.

**Comment by pei-jung** [comment]
Thanks @patriciajeanperez!

**Comment by pei-jung** [comment]
Changes sent in https://github.com/brianchandotcom/liferay-portal/pull/100829

**Pull request closed without merging**
