### PR TITLE
LPS-97363 The order of Japanese prefectures is incorrect in any area of Liferay that uses dynamically populated addresses

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-97363](https://issues.liferay.com/browse/LPS-97363).<br><br>Hey Pei-Jung, this uses database ordering instead of sorthing the list after the fact. It also adds a test case.<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@pei-jung to explain why I just pass in `null` in a88e2d4 if the country is not Japan:  The original code overloads and passes in `null` for the `OrderByComparator`, so the original behavior is preserved here.

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75553. Thanks!

**Pull request closed without merging**
