### PR TITLE
LPS-109111

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-109111

Improves LPS-105477 by allowing users with permission MANAGE_SUBORGANIZATIONS to be able to search for sub-organizations as well.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Test failures look unrelated @pei-jung

**Comment by pei-jung** [comment]
@brianikim I'll try to take a look at this sometimes this week.

**Comment by brianikim** [comment]
Hello @pei-jung ,

Not trying to rush you by any means. Any updates on the review?

Sincerely,
Brian Kim

**Comment by pei-jung** [comment]
Hi @brianikim, the fix looks good. Can you add a test for this?

**Comment by brianikim** [comment]
Of course. I will update this PR with the test.

**Comment by pei-jung** [comment]
Thank you!

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@pei-jung ,

Test has been added.

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85523. Thanks!

**Pull request closed without merging**
