### PR TITLE
LPS-90529 Improve experience of selecting custom field input type

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LPS-90529

https://issues.liferay.com/browse/LEXI-485 has been merged into Clay but Chema still needs to publish a new version of Clay before the styling will match the mockups.

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @pei-jung, `clay@2.10.0` was merged into `master` last week, so this should be good to advance

**Comment by pei-jung** [comment]
Nice! Thanks @jbalsas!

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69806. Thanks!

**Pull request closed without merging**
