### PR TITLE
Some changes to PrincipalException nested exceptions

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey @sergiogonzalez @topolik @juliocamarero @marcellustavares,

This pull, when sent to Brian will make some changes to classes of components your teams own. The changes are very simple: I asked Pei-Jung to create (nested) subclasses of PrincipalException so that there is more information when it's catched about the real reason for the exception being thrown. I would appreciate if you could take a look just in case you see something that you don't like. It should be fast since the changes are pretty straight forward. The most relevant commits are https://github.com/JorgeFerrer/liferay-portal/commit/c5c2582e75ae57e4c6e2ccae5c78e491410c2be7 and https://github.com/JorgeFerrer/liferay-portal/commit/c5c2582e75ae57e4c6e2ccae5c78e491410c2be7

**Comment by topolik** [comment]
For me it's fine, thank you.

-- tom +

**Comment by sergiogonzalez** [comment]
looks good to me too :smile:

**Comment by juliocamarero** [comment]
looks very good! :+1:

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/JorgeFerrer/liferay-portal/pull/544.

**Pull request closed without merging**
