### PR TITLE
LPS-115167

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @pei-jung 

Could you please review this pull request?

This modification ensures that only necessary User information is stored in the Workflow Context.

@drewbrokke
@topolik

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Changes look good. I'll forward it after @topolik reviews it.

**Comment by IstvanD** [comment]
Thank you @pei-jung for reviewing it.
Hi @topolik did you have a chance to take a look at it?

Thank you and best regards,
István

**Comment by topolik** [comment]
Looks good, thanks.

Dne út 16. 6. 2020 10:24 uživatel István András Dézsi <
notifications@github.com> napsal:

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
