### PR TITLE
LPS-125959 Dropping AccountGroupAccountEntryRel table should be a major version bump

### PR DESCRIPTION
**Pull request by alee8888**
@pei-jung @drewbrokke

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@alee8888 does the new table successfully create on upgrade? I'm having issues with my dev server because the table is not present.

**Comment by drewbrokke** [comment]
Do we need to move the SQL resource file too?

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1291

**Pull request closed without merging**
