### PR TITLE
LPS-83613

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-83613

From a "nobody owns this resource" perspective, I don't know if `0` for the ownerId makes sense, or if `defaultUser.getUserId()` (the default user owns itself) makes more sense. Please let me know if you'd prefer the latter, or if the current solution doesn't make sense.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hi @holatuwol,

Thanks for woking on this. Couple thoughts after looking into this. I'm not sure if we need an individual resource for the default user. I don't know what's the exact purpose of the default user. I'll need to double check with Jorge, but it looks like the default user is used for creating several system level resources (system roles, resource permissions, etc) and for providing default settings for new users and site displays. 

Since `UserService.getCompanyUsers` checks for companyAdmin role, I think instead of having a separate resource permission for the default user, maybe just check for the company admin role for the default user in `UserPermission`. We don't want any other users to have access to the default user except the company admins, which makes me wonder why the default user is included in the `getCompanyUsers`. Is there a use case for it? Maybe we should just exclude the default user from the list?

What do you think?

/cc @jorgeferrer @drewbrokke

**Comment by JorgeFerrer** [comment]
Hi Pei-Jung, Minhchau,

As far as I remember, the default user entry in the database it's just there to represent the guest user. Considering that, it should probably be never returned in a list of users and it also does not really seem to make sense to get it.

So I tend to agree with Pei-Jung that the solution to the original issue is just to prevent returning that user when invoking getCompanyUsers()

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
@pei-jung, @JorgeFerrer : I've made the suggested change to exclude the guest user from the return value of getCompanyUsers as well as other methods returning collections of users.

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61807. Thanks!

**Pull request closed without merging**
