### PR TITLE
LPS-123628 Throw exception when there are countries in the CommerceCountry table without ISO codes during upgrade

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by Sharryxue** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Try to retrigger the forward testing since the relevant test seems blocked for a while.

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
