### PR TITLE
[TECHNICAL-SUPPORT] LPS-101893

### PR DESCRIPTION
**Pull request by jonathanmccann**
@pei-jung,

Thanks for reviewing the previous pull. This one is updated to only implement the count method.

I noticed that the other search factory seems to have the same issue as of LPS-102604 - https://github.com/liferay/liferay-portal/blob/master/modules/apps/account/account-admin-web/src/main/java/com/liferay/account/admin/web/internal/dao/search/AccountUserDisplaySearchContainerFactory.java#L64-L77

I haven't tested it but I would assume it exhibits the same behavior. I wasn't sure if you'd want a separate LPS for that so I didn't include it here. Let me know though.

Thanks.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@jonathanmccann 

The other one will work fine because the `length` that's set on the BaseModelSearchResult is the total count (https://github.com/liferay/liferay-portal/blob/master/modules/apps/account/account-service/src/main/java/com/liferay/account/internal/retriever/AccountUserRetrieverImpl.java#L87-L88). The idea is to follow the new pattern in `SearchHits`, which contain the result list (sorted and paginated if specified) and the total hits.

We will apply the same pattern to accounts once we've implemented the search for AccountEntry.

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79426. Thanks!

**Pull request closed without merging**
