### PR TITLE
[TECHNICAL-SUPPORT] LPS-101893

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@jonathanmccann Thanks for fixing this!

Since we just need to set the correct count for the total, adding a new API to return only the count with `accountEntryPersistence .countByC_S` is sufficient. Can you make the change and resend? Thanks!

**Comment by jonathanmccann** [comment]
https://github.com/pei-jung/liferay-portal/pull/511

**Pull request closed without merging**
