### PR TITLE
LPS-65393 PortalInstances out-of-sync adding or removing company on cluster

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-65393](https://issues.liferay.com/browse/LPS-65393).<br><br>Hey @pei-jung, would you mind taking a quick look at this to make sure I didn't miss anything. Thanks!<br><br>/cc @mhan810 @istvansajtos @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
I had to remove the commit for JournalService because I forgot that journal is a sub-repo.

**Comment by mhan810** [comment]
Yep, that’s why I didn’t put it a commit for the journal piece.  Can you
guys sort out how to get the commit into the subrepo?

**Comment by drewbrokke** [comment]
Sure thing. I think once this gets merged we can just send a pull to that repo to get merged.

**Comment by pei-jung** [comment]
PR submitted to https://github.com/brianchandotcom/liferay-portal/pull/44365. Thanks!

**Pull request closed without merging**
