### PR TITLE
LPS-85420 Bulk export/delete for assets should resume when a single asset fails

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-85420](https://issues.liferay.com/browse/LPS-85420).

Hey @pei-jung, will you please let me know if there is a different approach I should take with this\? It seems pretty straightforward, but if there's a better place to handle the exception then I'd like to know. Thanks!

@dejuknow export was the only place I was able to reproduce the error. If there are more, I'll happily send a follow-up pull covering the rest of the cases.

/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
LGTM!

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
