### PR TITLE
LPS-127860 pathMain and portalURL is null when verification email is sent to the Anonymous user

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @pei-jung ,

Could you please review this pull request?

This is an additional commit for [LPS-127860](https://issues.liferay.com/browse/LPS-127860) that covers an edge case.

Thank you and best regards,
István

### CODE REVIEW

**Comment by Sharryxue** [comment]
Trigger the relavent test before review.

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:stable

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hi @pei-jung,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by pei-jung** [comment]
Hi @IstvanD,

Thanks for sending a fix for this. Is this edge case specifically for the Anonymous user? If so, we can leave it as is without fixing it. The [Anonymous user](https://learn.liferay.com/dxp/7.x/en/users-and-permissions/managing-user-data/configuring-the-anonymous-user.html) is not a real user but a dummy "system" user, similar to the Guest user. We use the Anonymous user to preserve user data during data anonymization. No one will ever log in as the system Anonymous user so its email address will never be verified. In this case, it's okay to have an invalid url in the verification email since nobody will receive the email. Ideally, we should not send an email for the Anonymous user, but it will be a different issue.

**Comment by IstvanD** [comment]
Hi @pei-jung 

Thank you very much for the explanation! I wasn't aware of the role of this peculiar user. :)
Given this information, I'm not insisting to add this edge case to the solution.

**Pull request closed without merging**
