### PR TITLE
LPS-116387 Add workflow support for account roles

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@pei-jung the `WorkflowException` seems like it could be a real failure.

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@patriciajeanperez these failures look similar to the ones in https://github.com/drewbrokke/liferay-portal/pull/1189#issuecomment-708599283. Are these flaky tests as well?

**Comment by patriciajeanperez** [comment]
yes, looks flaky @pei-jung I will re-run

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
