### PR TITLE
LPS-129699 Remove Liferay.Util.selectEntityHandler usages from roles

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hi Pei-Jung, sending you this because I can't find the home of Users & System Management team.

This PR removes usages of `Liferay.Util.selectEntityHandler` inside `roles-admin-web`. I've manually tested the changes to make sure modals work as they did before.

Initial PR can be found in https://github.com/liferay-frontend/liferay-portal/pull/950 where it has been initially reviewed.

## 🧪 Testing
1. Open the Control Panel and go to Users and Organizations
2. Create a new user
3. Click on Roles in the left navigation
4. `Select` Regular roles, and `Select` Site roles

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failure not related，re-trigger the relevant tests.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:stable

**Comment by kresimir-coko** [comment]
This should be ready for a forward, or a merge, not sure what the protocol is here @pei-jung @Sharryxue

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
