### PR TITLE
LPS-125331 Exception when deleting multiple addresses

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LPS-125331

@drewbrokke @pei-jung 
Patty fetched the fix, tested it locally, and it passed.

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:accounts

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
