### PR TITLE
LPS-82122 Cannot approve User in Workflow on 7.1 release bundles because of dependency on Directory module

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @pei-jung,

I've moved the User asset renderer into contacts-web, as directory-web
has been deprecated. It's not the ideal solution, but at least it will
allow the workflow to work properly.

I couldn't test this with the workflow, as it isn't working properly
for me. But I've checked that the user details are displayed correctly
by using the asset publisher.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test

**Comment by pei-jung** [comment]
Hi @adolfopa,

1. Shouldn't we move the organization asset renderer as well?
2. I'm not sure if the contacts portlet will stay around in portal for long. It was originally migrated for customers who have social office subscriptions. There have been plans to deprecate/remove this portlet, but I don't know when. AFAIK, not many people use that portlet. So it is pretty out-dated as you can tell from the UI. Because of that, I think it'd be more appropriate to move the asset renderers to users-admin-web.
3. Workflow works fine when I test. We might need to update the preview.

**`directory-web` UserAssetRenderer:**
screen shot 2018-06-08 at 6 11 25 pm

**`contacts-web` UserAssetRenderer:**
screen shot 2018-06-08 at 6 05 06 pm

Everything else looks good to me! 👍

**Comment by adolfopa** [comment]
Hey @pei-jung 

About the organizations asset renderer, I was going to move it as well, but the problem is that there's no good candidate target module. I haven't found any user facing JSP that displays the details of an organization (and the one in directory-web cannot be moved without moving 80% of the portlet :-( ).

I Agree that contacts is not a good place for this. In fact, at first I tried to move it into users-admin along with the org. asset renderer, but the problem is that all views in user-admin are intended for editing, not for viewing.

So, moving this into contacts-web is a quick and low risk way of transferring this to your team, and will allow WF (or anything that displays users with the asset framework) to work again for the release (even if it looks ugly as hell ;-) ).

Finally, about the organizations asset renderer, do you guys have any view that we can use for it? I can send you a similar pull for it, but we need some existing view that we can reuse. We don't have bandwidth to implement a new view for organizations.

Thank!

**Comment by pei-jung** [comment]
@adolfopa Thanks for the explanation. That makes sense. Since we don't have any other existing views that can be reused for user or organization, we will use your changes as a temporary fix for the release. We can work more on this, including the organization asset renderer, after the release.

I removed irrelevant fields from the user preview and sent your changes to Brian. Please see https://github.com/brianchandotcom/liferay-portal/pull/60097. Thanks!

**Comment by adolfopa** [comment]
Thanks a lot :-)

**Pull request closed without merging**
