### PR TITLE
[TECHNICAL-SUPPORT] LPS-68951

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-68951

Same pull than https://github.com/pei-jung/liferay-portal/pull/149 but I have removed a change done in `custom-sql/portal.xml` that was not necessary

> 
> Sybase has some problems with select count from a union:
> `select count(c) from ((select c from table1) union (select c from table2))`
> 
> To avoid sybase limitation I have added following commit: https://github.com/pei-jung/liferay-portal/pull/149/commits/a3f7de057b5d39edd32057a8103eb5788773b92b
> 
> This approach is similar to `UserFinderImpl.countByGroups` added in LPS-57748: https://github.com/brianchandotcom/liferay-portal/pull/30280

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by pei-jung** [comment]
Pull request submitted to Shuyang for review https://github.com/shuyangzhou/liferay-portal/pull/3445. Thanks!

**Pull request closed without merging**
