### PR TITLE
LPS-119458

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-119458

From @hongvo2308
> I found the cause of the bad performance is the doSearch function. It tries to fetch all Company, Group and Organization then It filters by site. So I decide to add site filter at fetching phase. And It has a good performance now.

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The SF issue is specific, @hongvo2308 would you please taking care? It seems caused by the laste commit message "LPs-119458 Semantic Versioning" which should be capital letter like LPS.
The [semantic-versioning-jdk8](https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/436849//consoleText) issue is addressed in [LPS-120151](https://issues.liferay.com/browse/LPS-120151).
/cc @pei-jung

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
Thanks @Sharryxue ! I've pushed an update with the suggested changes.

**Comment by pei-jung** [comment]
@patriciajeanperez are these real test failures?

**Comment by patriciajeanperez** [comment]
Hi @holatuwol, looks like portal-kernel needs a version bump too from changes made in d7c6ef2f816a73ba29d2e6de416aa4ab1adbeb34

**Comment by pei-jung** [comment]
updated versioning and testing in https://github.com/pei-jung/liferay-portal/pull/696

**Pull request closed without merging**
