### PR TITLE
[TECHNICAL-SUPPORT] LPS-68951

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-68951

Sybase has some problems with select count from a union:
`select count(c) from ((select c from table1) union (select c from table2))`

To avoid sybase limitation I have added following commit: https://github.com/pei-jung/liferay-portal/pull/149/commits/a3f7de057b5d39edd32057a8103eb5788773b92b

This approach is similar to `UserFinderImpl.countByGroups` added in LPS-57748: https://github.com/brianchandotcom/liferay-portal/pull/30280

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Hi @pei-jung 

Do you have any update about this pull request?

Thank you,
Jorge Díaz

**Comment by pei-jung** [comment]
Hi @jorgediaz-lr,

Sorry for the delay in reviewing this pr. I'll take a look at it today.

**Comment by jorgediaz-lr** [comment]
Thank you @pei-jung

**Comment by pei-jung** [comment]
PR submitted https://github.com/JorgeFerrer/liferay-portal/pull/797 for further review. Thanks!

**Pull request closed without merging**
