### PR TITLE
LPS-125959 Update AccountGroupAccountEntryRel to AccountGroupRel

### PR DESCRIPTION
**Pull request by alee8888**
@drewbrokke

https://issues.liferay.com/browse/LPS-125959

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:reevaluate:1032004_8988

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
