### PR TITLE
LPS-90534 Set default display property for all types

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-90534

- I amended commit 
[LPS-90534 Remove custom field presets](https://github.com/pei-jung/liferay-portal/pull/348/commits/76cf17e566918f81d7cd3c649d0134aa761ea34d) to keep and deprecate `ExpandoPresetUtil.java`
- Additional commit https://github.com/pei-jung/liferay-portal/pull/348/commits/a2d3252c747f4e4a60d36aa74a9619b6e46738dc to add the helper method in `ExpandoColumnConstants.java`

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by thektan** [comment]
I'll wait until the ci relevant tests complete to push up the sf fix.

**Comment by thektan** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
Hey Kevin,

I added back your changes to the document library extra settings back in https://github.com/brianchandotcom/liferay-portal/pull/68835/commits/889ba8a155414c82a0fe8647a58417f3506d98c5 since this is is still referenced in [DocumentLibraryExtraSettingsConvertProcess](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/convert/documentlibrary/DocumentLibraryExtraSettingsConvertProcess.java).

I also made a minor change for optimization so that we can save a method call when the default value is not needed. Please see 
https://github.com/brianchandotcom/liferay-portal/pull/68835/commits/47a26d7716735d26caf8347237bfc3f473bde829.

Everything else looks good! Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68835. Thanks!

**Pull request closed without merging**
