### PR TITLE
LPS-90264 Remove User Personal Bar from Product Menu and optionally add to Control Menu

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:stop

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
@pei-jung I think this might be good? This failure looks unrelated

**Comment by pei-jung** [comment]
@stsquared99 yup, the test results look good. I'll review it now.

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70551. Thanks!

**Pull request closed without merging**
