### PR TITLE
[TECHNICAL-SUPPORT] LPS-52107

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @wanderlast

Hello @pei-jung, this is a resend of https://github.com/pei-jung/liferay-portal/pull/231 addressing the concerns you had with it. Thank you.

Notes from Lianne:
> LPP: https://issues.liferay.com/browse/LPP-28259
> LPS: https://issues.liferay.com/browse/LPS-52107
> 
> **Issue:**
> The issue being reported by the client is that child organizations do not inherit site membership from parent organizations. 
> 
> **Summary of History:**
> A previous LPP provides context for this fix. Specifically several decisions were made including:
> - that the behavior of children organizations being added automatically is [intended](https://issues.liferay.com/browse/LPP-14323?focusedCommentId=548245&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-548245)
> - that [users belonging to child orgs should be visible](https://issues.liferay.com/browse/LPP-14323?focusedCommentId=556942&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-556942) in Site Memberships -> Users upon being added through a parent org being added
> 
> A previous PR also outlined that the fix should work on preexisting organizations/sites, that it should account for a child organization being added to a parent organization after the membership is established, as well as automatic removal of all children if a parent is removed.
> 
> **The Fix:**
> The fix involves checking if the children organizations of all site member organizations are members of the group on page load and adding them if they are not. Children organizations are also added when a parent organization is added and correspondingly removed when the parent is removed. This behavior only works for the 'highest tier' member in the relationship chain--so if Liferay Europe is added, then Liferay Spain is added as a member as well. However, if Liferay Global is added later, Liferay Europe is no longer considered independent and cannot be removed unless Liferay Global is removed. This means that inheritance is strictly enforced as mandatory and individual users and individual child organizations cannot be removed.
> 
> The fix itself uses a portal property to allow the user to determine the behavior they wish to have. It defaults to false which corresponds to how the portal works presently (inheritance does not occur). If set to true, inheritance will be enforced.
> 
> Please let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by wanderlast** [comment]
Hi @pei-jung, do you know when you might have a chance to look at this PR?

**Comment by pei-jung** [comment]
@wanderlast i'll take a look at this PR tomorrow

**Comment by pei-jung** [comment]
Hi @wanderlast,

Thanks for working on the issue. However, I don't think the proposed solution is ideal because it adds more complication to the organization hierarchies and can create more confusion to the end users.

> Children organizations are also added when a parent organization is added and correspondingly removed when the parent is removed.

This can be problematic if the child organization is added intentionally. 

> This behavior only works for the 'highest tier' member in the relationship chain--so if Liferay Europe is added, then Liferay Spain is added as a member as well. However, if Liferay Global is added later, Liferay Europe is no longer considered independent and cannot be removed unless Liferay Global is removed. This means that inheritance is strictly enforced as mandatory and individual users and individual child organizations cannot be removed.

According to your previous statement where children orgs are automatically removed when the parent org is removed, what happens to the n-th level descendent ogs? In your example, does Liferay Spain gets removed when Liferay Global is removed? 

With some debugging, I found out that [GroupService.getUserSitesGroups](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/GroupServiceImpl.java#L522-L523) indicates that it includes the user's immediate organization groups and site groups. Yet, the `userBag` that it references uses [GroupLoalService.getUserGroups(userId, inherit=true)](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/GroupLocalServiceImpl.java#L1741-L1751), which should include the user's inherited organization groups but it doesn't. I think this is where the fix should be...

Unfortunately, I didn't have time to dig too deep into this. Let me talk to Jorge to get his opinion on your fix, and I will get back to you.

/cc @jorgeferrer

**Comment by wanderlast** [comment]
Hi @pei-jung,

Thanks for looking at this for me! To answer your question, yes, Liferay Spain would also be removed. All n-th level descendents are removed. I'll wait for your and Jorge's response before looking at this again.

**Comment by pei-jung** [comment]
Hi @wanderlast,

We don't want this behavior to happen because it's very error prone and can lead to undesired outcomes. As Jorge pointed out, if Org A1 is a member of site X. Then Org A (which is a parent of A1) is made a member accidentally. The error is quickly corrected by removing A, which causes all of its child orgs (including A1) to be removed as a member.

After checking with Jorge, we believe the best approach for solving this issue will be doing a more complex query to account for the parent organizations when checking for site memberships. If you trace down the group search from `MySitesItemSelectorViewDisplayContext`, it calls `GroupLoalService.getUserGroups` to get all the user's site groups. From the method javadoc, It looks like `GroupLoalService.getUserGroups` should return all the sites that the user belongs to both directly and indirectly when _inheritance=true_. So if it’s not returning the site where a parent org is a member then it should. And since site membership is owned by the web experience team, I'd like to ask you to double check with @ealonso to make sure what I just mentioned is the expected behavior because we'll need to apply this to everywhere site membership is checked.

Please let me know if you have any questions. Thanks again for taking care of this!

**Pull request closed without merging**
