### PR TITLE
[TECHNICAL-SUPPORT] LPS-105583

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @holatuwol @hhtank:

> https://issues.liferay.com/browse/LPS-105583
> 
> In order to resolve the error, I think the best approach is to remove the connection between the screen name and the user personal page friendly URLs. Please let me know if you have any concerns, or if you believe we should try a different approach.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by hhtank** [comment]
Hello @pei-jung,
I know you are off for holiday season. But there is an milestone from the customer. Is there any chance that you could review this PR when you're back from vacation? This PR changes core behavior in creating new Users, so that TS team did not want to give an SDH to the customer before it's approved by product team.
Feel free to let me know if you have any concerns or questions.
Thank you!

**Comment by pei-jung** [comment]
Reviewed and forwarded to https://github.com/drewbrokke/liferay-portal/pull/945. Thanks.

**Pull request closed without merging**
