### PR TITLE
LPS-129587 Migrate selection modals in users-admin

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hi @pei-jung, I'm forwarding this to you after getting some eyes on it at https://github.com/liferay-frontend/liferay-portal/pull/969. 

This PR migrates selection modals in `users-admin-web`, which caused the regression with these modals 10 days (or so) ago. There is a usage inside `site-browser-web` package that is related to some of the modals here in `users-admin` so I've included that as a separate commit.

# 🧪 Testing
## `site-browser-web/view.jsp` - `sites.jsp` modal
1. Create a new user and then edit it
2. Go to `Memberships` of that user
3. Click on `Select` in the `Sites` section

## `users-admin-web/select_organization.jsp` - `organizations.jsp` modal
1. Create an organization
2. Go to the previously created user and go to their `Organizations`
3. Click on `Select` in the `Organizations` section

## `users-admin-web/select_organization_users.jsp` - `users-admin-web/actions#selectUsers` modal
1. Go to the Organizations tab
2. Assign Users to your Organization
3. Select your existing user/s to add to the Organizations
4. Users are added to the Organization

## `user_item_selector.jsp`
_I haven't been able to find a usage of this file inside the Commerce Account portlet_. The other usage can be found:
1. Go to Site Admin Menu > People > Segments
2. Add a new user segment
3. Drag the User property from the sidebar to Conditions
4. Click on Select

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:usm

**Comment by pei-jung** [comment]
Hi @kresimir-coko 

Overall the changes look good, but the change to the user_item_selector.jsp breaks the usage in commerce account: [commerce-account-admin-web - account/users.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/commerce-account-admin-web/src/main/resources/META-INF/resources/account/users.jsp)

1. Go to Control Panel > Accounts (under the Users category)
2. Add an account
3. In the edit account view, go to the Users tab
4. Click on the plus button to assign users to the account
5. Select an user

The `Add` button is disabled, so users cannot be assigned to account.

Screen Shot 2021-04-26 at 4 57 44 PM

**Pull request closed without merging**
