### PR TITLE
LPS-98850 Add Account Groups category and app to the Control Panel in the product menu

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LPS-112598

@jonmak08

### CODE REVIEW

**Comment by jonmak08** [comment]
LGTM.  Thanks @alee8888!

**Comment by alee8888** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/pei-jung/liferay-portal/pull/629. Thanks!

**Pull request closed without merging**
