### PR TITLE
[TECHNICAL-SUPPORT] LPS-104337

### PR DESCRIPTION
**Pull request by jonathanmccann**
@pei-jung @dejuknow

Thank you for the outline on the previous pull. I believe I included everything but please let me know if I overlooked something.

There are two other caveats I discovered when testing that might be good to document somewhere:

1. If a client wants to translate a mutli-word phrase then the name will need to be separated by dashes instead of spaces in order for it to be found in the language properties.
2. Since the custom field can be displayed in multiple places the global `language.properties` file will need to be overridden and not the one within `expando-web`.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@pei-jung Have you been able to take a look at these changes?

**Comment by pei-jung** [comment]
@jonathanmccann not yet. I'll review this today.

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81778. Thanks!

**Comment by pei-jung** [comment]
@rbohl Please see Jonathan's comment above. We need to include those in the docs for custom fields. Thanks!

**Comment by rbohl** [comment]
Tracking here: https://issues.liferay.com/browse/LRDOCS-7508

**Pull request closed without merging**
