### PR TITLE
LPS-130454 | master

### PR DESCRIPTION
**Pull request by davidtellolr**
Hi @pei-jung  ,

This PR resolves the LPS-130454. 

These modifications are to handle an uncaught null pointer exception to be able to finish the users export. I decided to return null in the method ExpandoValueServiceImpl.getData if the column does not exist because I saw that is the class code's primary strategy. This "null" answer is managed in ExportUsersMVCResourceCommand to generate a correct CSV.

Please, let me know if you have any doubts.

Thanks

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failure in [lpkg-controller-jdk8/0](https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/468452/) not related.

**Comment by marianoalvarosaiz** [comment]
@pei-jung did you have time to take a look to this PR?

**Comment by pei-jung** [comment]
@marianoalvarosaiz sorry for the delay. We have a team github user for handling pull request review now. Please send any future request to @liferay-usm for review. 

I added a test for this issue and sent it to https://github.com/liferay-usm/liferay-portal/pull/47 for ci testing. Once it passes ci, I'll forward it to Brian. Please let me know if you have any questions. Thanks!

**Comment by marianoalvarosaiz** [comment]
@pei-jung thanks a lot. I've seen that https://grow.liferay.com/group/guest/people/-/wiki/34277/SME+Master+List has also been update with the liferay-usm

**Pull request closed without merging**
