### PR TITLE
LPS-109676 Asset Library permissions configuration should be scoped to Asset Library roles

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-109676](https://issues.liferay.com/browse/LPS-109676).

### CODE REVIEW

**Comment by drewbrokke** [comment]
@pei-jung will you please look over my change at 9b5bd3dee377753cb02096d4c16a9e73977e034d and let me know if you're ok with it? Thanks!

**Comment by pei-jung** [comment]
@drewbrokke LGTM, thanks for catching that!

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez what are our options for the failing functional tests here?

cc @adolfopa @cgoncas

**Comment by patriciajeanperez** [comment]
Looking into the test failures cc @adolfopa @cgoncas @drewbrokke

**Comment by patriciajeanperez** [comment]
Depot tests have been quarantined, Roles tests are failing from 
`    [exec] 23:10:36,706 ERROR [http-nio-8080-exec-2][PortletRequestDispatcherImpl:304] Unable to dispatch request: java.lang.NullPointerException
     [exec] 23:10:36,707 ERROR [http-nio-8080-exec-2][PortletConfigurationPortlet:687] org.apache.jasper.JasperException: java.lang.NullPointerException
     [exec]     LIFERAY_ERROR: Unable to dispatch request: java.lang.NullPointerException
     [exec]     LIFERAY_ERROR: org.apache.jasper.JasperException: java.lang.NullPointerException`

Permission modal is empty for site team members. 

@pei-jung is taking a look.

cc @drewbrokke

**Comment by pei-jung** [comment]
Fixed the role test failures and testing in https://github.com/pei-jung/liferay-portal/pull/593

**Pull request closed without merging**
