### PR TITLE
LPS-115260 As an account manager, I want to create account users from an account's details page

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-115260](https://issues.liferay.com/browse/LPS-115260).<br><br>Hey Pei, I went ahead and removed the namespacing. I didn't get an answer on it so I'm gonna play it safe for now.<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
LGTM 👍

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
