### PR TITLE
LPS-108998

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
Hi @pei-jung 
Based on [this comment](https://issues.liferay.com/browse/LPS-108998?focusedCommentId=2102575&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2102575) , I add `company.security.strangers.verify=false` into legacy property files.
So I send another PR to you.

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86201. Thanks!

**Pull request closed without merging**
