### PR TITLE
[TECHNICAL-SUPPORT] LPS-110563

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-110563

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
Note that tests were passing at https://github.com/wanderlast/liferay-portal/pull/57

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
See brianchandotcom#87438. Thanks!

**Pull request closed without merging**
