### PR TITLE
LPS-75377 Add language keys for categories, category sets and scopes

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Hey Pei-Jung, this is the second part of the changes to support the new System Settings UI. I still need to make a few changes, but I'd prefer it if you can review it up until here and send me a pull if you make any changes. Also, could you check with Albert or Brian Lee if it will be necessary to change any POSHI tests as a result of these UI changes?

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test

**Comment by JorgeFerrer** [comment]
ci:open

**Comment by JorgeFerrer** [comment]
@pei-jung I'll check with Ray the reason for the baseline failure. The other errors seem unrelated.

Also, when you review the pull, be aware that there are some spacing issues right now, but don't worry about them. Marcos Castro is going to help me fix them next week.

**Comment by pei-jung** [comment]
Reviewed and sent to https://github.com/JorgeFerrer/liferay-portal/pull/838. Thanks!

**Pull request closed without merging**
