### PR TITLE
LPS-108998

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@yxingwu can you take a look at the failures? I think they might be related to your change.

**Comment by yxingwu** [comment]
ci:retest:sf

**Comment by yxingwu** [comment]
ci:retest:relevant

**Comment by yxingwu** [comment]
Hi @pei-jung ,
I've forced update the PR, please review it again.

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86061. Thanks!

**Pull request closed without merging**
