### PR TITLE
LPS-89274 Service builder will fail if an entity has partial uad attribute usage

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-89274](https://issues.liferay.com/browse/LPS-89274).<br><br>Hey Pei-Jung, can you please double-check this for me?  Let me know if you have any questions.<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian @Preston-Crary

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@drewbrokke can you merge 44c7cd4 and af626d6? The 2nd commit just reverts the first.

**Comment by drewbrokke** [comment]
@Preston-Crary just pushed the change.  LMK if it's good.

**Comment by pei-jung** [comment]
Closing as Drew is going to work on generating the build.gradle file with service builder.

**Pull request closed without merging**
