### PR TITLE
LPS-125622 Localize Region name field

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by pei-jung** [comment]
Hey @drewbrokke,

Do you mind take a quick look at my changes to make sure I didn't miss anything? Thanks!

**Comment by pei-jung** [comment]
@patriciajeanperez can I re-run the relevant tests?

**Comment by patriciajeanperez** [comment]
Looks like we can re-run. @pei-jung 

ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@patriciajeanperez is there any unique test failures related to my changes?

**Comment by patriciajeanperez** [comment]
Hi Pei! 

The upgrades tests didn't run due to this error:
`04:02:15,660 ERROR [main][MainServlet:302] java.lang.RuntimeException: You must first upgrade the portal to the required schema version 10.0.0
java.lang.RuntimeException: You must first upgrade the portal to the required schema version 10.0.0`

There are also these errors:
`03:13:07,212 ERROR [main][UpgradeMVCCVersion:57] Table CountryLocalization does not exist
03:13:07,286 ERROR [main][UpgradeMVCCVersion:57] Table RegionLocalization does not exist`

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by pei-jung** [comment]
@patriciajeanperez I don't see any upgrade failures related to Country or Region. Can you confirm?

**Comment by patriciajeanperez** [comment]
Hi @pei-jung, you're right. Failures are not related. Can I manually forward?

**Comment by pei-jung** [comment]
@patriciajeanperez great! Let me try ci:forward first.

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
