### PR TITLE
LPS-124350 Creating an account specific role displays in all accounts

### PR DESCRIPTION
**Pull request by alee8888**
@drewbrokke

https://issues.liferay.com/browse/LPS-124350

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @alee8888 
The failed integration test seems related to the changes made in here, would you please take a look into the issue? Thanks

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
