### PR TITLE
LPS-91588

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-91588

User screenname/friendlyURL duplication check is already done [here](https://github.com/pei-jung/liferay-portal/compare/master...ChrisKian:LPS-91588?expand=1#diff-aed545163a3676249d8003fbb6a4e6a9R4996), so there is no need to do it again.  By removing this second unnecessary check, we are able to avoid the issue described in LPS-91588 which relates specifically to DB2 column sizes.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:s

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/69973

**Pull request closed without merging**
