### PR TITLE
LPS-115260 As an account manager, I want to create account users from an account's details page

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-115260](https://issues.liferay.com/browse/LPS-115260).<br><br>Hey Pei, will you please look over my work on this one\? A few of the commits attempt to make the pattern more consistent across the JS components, so please let me know what you think about that. Thanks!<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failed functional tests can be passed on local by fetching the commits in this pull, 
* [LocalFile.BusinessAccounts#AddAccountUser](https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/410475//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_BusinessAccounts_AddAccountUser_) - pass on local
* [LocalFile.BusinessAccounts#DeleteAccount](https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/410475//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_BusinessAccounts_DeleteAccount_)  - pass on local
* [LocalFile.BusinessAccounts#UnassignOrganizationFromAccount](https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/410475//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_BusinessAccounts_UnassignOrganizationFromAccount_)  - pass on local

**Issue found on local**
Got following error on console when navigating to add account/user page, not pretty sure if it relates the commits here, the issue not reproducible on master upstream. Didn't find the same error message on portal
```
2020-07-10 11:10:51.018 ERROR [http-nio-7080-exec-4][JSONWebServiceServiceAction:114] com.liferay.portal.security.service.access.policy.exception.NoSuchEntryException: No SAPEntry exists with the key {companyId=20098, name=SYSTEM_DEFAULT}
2020-07-10 11:10:51.242 ERROR [http-nio-7080-exec-7][JSONWebServiceServiceAction:114] com.liferay.portal.security.service.access.policy.exception.NoSuchEntryException: No SAPEntry exists with the key {companyId=20098, name=SYSTEM_DEFAULT}
```

Based on above analyse result, will retrigger the relevant test.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
See https://github.com/pei-jung/liferay-portal/pull/660

**Pull request closed without merging**
