### PR TITLE
[TECHNICAL-SUPPORT] LPS-90727

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
This issue has been fixed by LPS-92213. @jonathanmccann @pei-jung either of you can close this one

**Comment by jonathanmccann** [comment]
@drewbrokke For future reference, you can comment "ci:close" on someone else's pull and it will close it.

**Comment by drewbrokke** [comment]
@jonathanmccann ah yeah, forgot about that.  Thanks!

**Pull request closed without merging**
