### PR TITLE
[TECHNICAL-SUPPORT] LPS-68988

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-68988

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by pei-jung** [comment]
PR submitted to https://github.com/JorgeFerrer/liferay-portal/pull/796 for further review. Thanks!

**Pull request closed without merging**
