### PR TITLE
LPS-116762

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @pei-jung ,
Could you please review this pull request?
According to WEM team, the solution seems to be more related to U&SM than to WEM.
Original LPP: https://issues.liferay.com/browse/LPP-38157
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by pei-jung** [comment]
Hi @MarcellGyopos, I wasn't able to finish reviewing the changes today. I'll try to get the review done tomorrow.

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Triggered the CI test before reviewing started.

**Comment by MarcellGyopos** [comment]
I'm working on the SF issues, I didn't get them in my local env.

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Retrigger the CI test for new commits come in.

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Pull request closed without merging**
