### PR TITLE
LPS-107640

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hi @patriciajeanperez, can you take a look at the two failing functional tests? My fix should have fixed the index issues. It works when I test locally, but it seems like it doesn't apply in the poshi tests.

**Comment by patriciajeanperez** [comment]
Hi @pei-jung, looking at the console output, the console errors described in LPS-107640 are still present. Can you please take a look?

**Pull request closed without merging**
