### PR TITLE
LPS-121997 Update service.xml and add Upgrade processes for Country

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@alee8888 @pei-jung looks like you also need to add an upgrade process to add the `CountryLocalization` table to the database.

**Comment by alee8888** [comment]
Resent here https://github.com/pei-jung/liferay-portal/pull/731

**Pull request closed without merging**
