### PR TITLE
LPS-122668 Implement search for Address

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-122668](https://issues.liferay.com/browse/LPS-122668).

Hey @pei-jung, I made a couple of refactors and added error logging for invalid list type names. Will you please double-check my work on this\? If it looks good then we can forward.

/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
See https://github.com/pei-jung/liferay-portal/pull/733

**Pull request closed without merging**
