### PR TITLE
J cords lps 73201 revert

### PR DESCRIPTION
**Pull request by joshuacords**
Hello @pei-jung, 
After testing, the changes made in da20fa90824a did not keep the intended functionality. Even though Timestamp is a subclass of Date, the toString method continues to function differently even when upcasted. I reverted this change and added a simplify commit which follows your basic format. Let me know if you have any questions.

### CODE REVIEW

**Comment by pei-jung** [comment]
Hi @joshuacords,

I just tested this again on master, the timestamp is printed in the java date format `Mon Jun 26 19:43:27 GMT 2017`. Did you take different steps when you tested this?

**Comment by joshuacords** [comment]
I used the steps in LPS-73201. The most important being: create a User, clear the Database cache; then Export Users. I get the following result from master d2eed9450eef8c320a7c7e81461ffab0d93f3505: 
csv master failed

**Comment by pei-jung** [comment]
@joshuacords, I also followed the same steps in the ticket and at the same SHA, d2eed94. This is what I got after I created the users, cleared the db cache, and exported:

[users (7).txt](https://github.com/pei-jung/liferay-portal/files/1103616/users.7.txt)

**Comment by joshuacords** [comment]
So my exact steps were: 
1. Checkout and deploy master at d2eed9450eef8c320a7c7e81461ffab0d93f3505
2. Gradle clean deploy modules/apps/foundation/users-admin/users-admin-web 
3. Delete my osgi/state and tomcat/work, tomcat/temp folders
4. Set portal-ext.properties to have:
 users.export.csv.fields=firstName,lastName,createDate,modifiedDate,passwordModifiedDate,loginDate,lastLoginDate,lastFailedLoginDate,lockoutDate
(I'm testing all Date fields)
5. Follow LPS-73201 steps 2-9
Here's the output I'm getting:
csv export results

I know Sam Ziemer had a problem replicating the issue at one point, but we walked through it together and it worked then. I'm not sure what the difference could be. 

Right now I'm using Tomcat-8.0.32 with a hsql database (but I know the original problem appears in MySQL database as well).

Could you try breakpointing this line: https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/users-admin/users-admin-web/src/main/java/com/liferay/users/admin/web/portlet/action/ExportUsersMVCResourceCommand.java#L124
When I step through it, if the User date is a Timestamp it will keep the Timestamp format. Can you confirm on your machine that the code is properly converting the Timestamp format to a Date format?

**Comment by pei-jung** [comment]
Please see https://github.com/joshuacords/liferay-portal/pull/1.

**Pull request closed without merging**
