### PR TITLE
LPS-113856 There should be a Manage Suborganizations Accounts permission in Account Entry

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez looks like the failure is unrelated. Should I re-run the tests?

**Comment by patriciajeanperez** [comment]
Yes, it looks like a network issue. I will re-run. @pei-jung

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
