### PR TITLE
LPS-127860 URL in mail verification has 'nullnull' after creating a new virtual instance

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @pei-jung 

Could you please review this pull request?

This code set the missing `portalURL` and `pathMain` parts of the verification URL.
However, I couldn't figure out a way the get the server port because no `request` object is available.

Are there any services in our codebase that can be used to determine the port without `request`?

@drewbrokke

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failed functional test is more like fluke, retrigger the relavent test.

**Comment by pei-jung** [comment]
Hi @IstvanD, you can use `PortalUtil.getPortalServerPort` to get the server port. There's also an convenient method in CompanyImpl that gets you the portal url with the port, see [CompanyImpl.getPortalURL](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/CompanyImpl.java#L215-L253).

PR will be forwarded in https://github.com/pei-jung/liferay-portal/pull/789. Thanks!

**Comment by IstvanD** [comment]
Hi @pei-jung thank you, I didn't know that. :)

**Pull request closed without merging**
