### PR TITLE
LPS-124798 AssertionError for CountryLocalServiceTest

### PR DESCRIPTION
**Pull request by alee8888**
@drewbrokke @pei-jung

https://issues.liferay.com/browse/LPS-124798

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
No unique failure for this pr.
Issue in [rest-builder-jdk8/0](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/211093/) is addressed in [LPS-124733](https://issues.liferay.com/browse/LPS-124733) and fixed by [commit](https://github.com/brianchandotcom/liferay-portal/pull/96861).
Will retrigger the relavent test since the above commit is  merged already.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
