### PR TITLE
LPS-101097 Create an API method to retrieve all users for an account

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-101097](https://issues.liferay.com/browse/LPS-101097).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/78509.

**Pull request closed without merging**
