### PR TITLE
LPS-97381 Personal Data Erasure does not accurately display count of applications

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-97381](https://issues.liferay.com/browse/LPS-97381).<br><br>Hey Pei-Jung, will you please double-check my work on this one\? Please let me know if you have any questions. Thanks\!<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76299. Thanks!

**Pull request closed without merging**
