### PR TITLE
[TECHNICAL-SUPPORT] LPS-78227

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @Alec-Shay

This issue is currently blocked by
https://issues.liferay.com/browse/LPS-78877

Notes from Alec:

> Relevant tickets:
> 
> https://issues.liferay.com/browse/LPP-28913
> https://issues.liferay.com/browse/LPS-78227
> https://issues.liferay.com/browse/PTR-269
> 
> Viewing Organizations through either the Control Panel portlet or through "My Organizations" cannot show non-root Organizations by default (without searching). Additionally, if searching with index is disabled through use of the property `organizations.search.with.index=false`, then the results will differ in that child Organizations can be returned and viewed this way, when searching with index will not do so.
> 
> After discussion on [PTR-269](https://issues.liferay.com/browse/PTR-269), it was decided that the configuration to allow searching without index should be removed from master, although for released versions, we will push for consistency. To do this, the change introduced here makes searching without index (in `OrganizationFinderImpl`) remove the wild card from the organizationsTree that allows returning child Organizations.
> 
> Additionally, for usability purposes, we made a change to make the `parentOrganizationId` match any Organization when none is specified and there are no search terms (so, when the Organizations are first loaded). That way, non-root Organizations can be viewed without having to search explicitly for them, which should be less confusing for members of those Organizations.
> 
> See [this comment](https://issues.liferay.com/browse/PTR-269?focusedCommentId=1253417&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1253417) (and the following discussion) for more on our reasoning.
> 
> Let me know if there are any questions or concerns. Thanks!

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by Alec-Shay** [comment]
Hello @pei-jung,

The issue blocking testing for this ([https://issues.liferay.com/browse/LPS-78877](url)) no longer seems to be reproducible. Will you be able to take a look at this soon?

Thanks.

**Comment by pei-jung** [comment]
@Alec-Shay Sorry for the delay. I'll try to look at this today.

**Comment by pei-jung** [comment]
Hi @Alec-Shay,

If I understand the solution proposed in [PTR-269](https://issues.liferay.com/browse/PTR-269) correctly, we want to keep the existing behavior of organization search and change the finder to match the behavior of the indexer. So the expected behavior is to display only the root level orgs, or the top most org in the hierarchy if the user doesn't have access to the root org. However, with your change in 2997f14, all organizations will be displayed, including both root level orgs and sub-orgs. I'm not sure if that's a desirable behavior. I remember there was a ticket complaining about performance when displaying all levels of organizations in the view. I tried to look for that ticket but couldn't find it.

This is not caused by your change, but when searching for sub-organizations, if the user has admin rights, the sub-org should be returned in the results even if the user is not directly assigned to it.

**Comment by Alec-Shay** [comment]
Hello @pei-jung,

I'm not sure whether I have understood this correctly. I've read through [PTR-269](https://issues.liferay.com/browse/PTR-269) again but I cannot find the suggestion that the expected behavior is to only show root-level organizations or the top-most organization in the hierarchy -- nor does it seem like that would that make the finder behavior match that of the indexer, if it did work that way (and this change is mostly aimed at maintaining consistency between the two approaches). I could see a performance impact if we had to traverse the organizations tree to find the top-most organization, but I don't see any mention of that approach on the PTR, so I'm confused about whether this means I've taken away the wrong conclusion from the ticket altogether.

My understanding was that, while searching with the finder and not with the index will not be supported in the future, we would just want to push for consistency -- and the consistent behavior is for 

> So the expected behavior is to display only the root level orgs, or the top most org in the hierarchy if the user doesn't have access to the root org.

> This is not caused by your change, but when searching for sub-organizations, if the user has admin rights, the sub-org should be returned in the results even if the user is not directly assigned to it.

I'm sorry, but I'm really confused by this. Should it only display the root level or top-most organization (like in the first statement), or should it also display the sub-organizations (like in the second statement)?

**Comment by Alec-Shay** [comment]
@pei-jung Hmm... Okay, I think I understand. That change is not needed for consistency between index and finder search. I thought the discussion on PTR-269 was recommending we make the change to the parameters for both as well, but possibly I misunderstood this.

The other change, though, 8c398de, is strictly aimed at changing the finder behavior to match that of the index search. The index search does not return child organizations of those the user belongs to, whereas the finder search does because of the way it forms the query.

Would it still make sense to do that change then, possibly, just without the change to the parent organization ID parameter?

**Comment by pei-jung** [comment]
> The other change, though, 8c398de, is strictly aimed at changing the finder behavior to match that of the index search. The index search does not return child organizations of those the user belongs to, whereas the finder search does because of the way it forms the query.

Yes. If the goal is to force consistency between the indexer and the finder, it makes sense to have this change.

**Pull request closed without merging**
