### PR TITLE
[TS] LPS-122283 Set groupIds to -1 so that the GroupIdQueryPreFilterContributor will not include the Active/InactiveGroupsBooleanFilter since Users and Organizations don't belong to any of them themselves

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-122283

If you have inactive groupIds, they are added to the search query by the GroupIdQueryPreFilterContributor.

That can cause problems if you have a large number of inactive users (because users have an entry in group_ table).

Users and Organizations doesn't have any groupId indexed in the Elasticsearch, so it is worthless to add this filter, to avoid adding this filter, we can set this filter to "-1", that will disable the groupId filter that is added in GroupIdQueryPreFilterContributor.

The same solution of filtering using "-1" value is already applied in both the segmentation and workflows functionalities, see:

- Segmentation: https://github.com/liferay/liferay-portal/commit/7a8a2bdf3fa9024512484264756b1922f2fc0438
- Workflow:  https://github.com/liferay/liferay-portal/commit/e35d2a5b1743663cd13f3f14030772b0abaa339f

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @pei-jung 

Do you have any update about this PR?

Let me know if you have any question.

Regards,
Jorge

**Comment by pei-jung** [comment]
hi @jorgediaz-lr,

Sorry for the delay in reviewing this. The change looks good to me. I'll go ahead and forward it to Brian.

**Comment by pei-jung** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
Thanks @pei-jung !

**Pull request closed without merging**
