### PR TITLE
LPS-123628 As an administrator, I want to pre-populate countries and regions used by both Portal and Commerce

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by Sharryxue** [comment]
Related failure:
1 There're console error like following seems related to the commits. Refer [console](https://testray.liferay.com/reports/production/logs/test-1-11/1616052080486/test-portal-acceptance-pullrequest(master)/8589/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz)
```
    [junit] 2021-03-18 08:44:45.455 ERROR [main][JDBCExceptionReporter:234] Duplicate entry '20927-54.0' for key 'IX_A2635F5C'
    [junit] 2021-03-18 08:44:46.136 INFO  [fileinstall-directory-watcher][BaseAutoDeployListener:43] Copying hook plugin for /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.43/temp/20210318084446122FEQOVRNK/documentum-hook.war
    [junit] 2021-03-18 08:44:46.168 INFO  [fileinstall-directory-watcher][BaseDeployer:874] Deploying documentum-hook.war
    [junit] 2021-03-18 08:44:46.516 INFO  [fileinstall-directory-watcher][BaseAutoDeployListener:50] Hook for /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.43/temp/20210318084446122FEQOVRNK/documentum-hook.war copied successfully
    [junit] 2021-03-18 08:44:48.259 ERROR [main][JDBCExceptionReporter:234] Duplicate entry '21103-CS' for key 'IX_A2635F5C'
    [junit] 2021-03-18 08:44:48.566 ERROR [main][JDBCExceptionReporter:234] Duplicate entry '21138-BE' for key 'IX_A2635F5C'
```

**Pull request closed without merging**
