### PR TITLE
LPS-90259 Create hidden pages for user apps belonging with Dashboard theme

### PR DESCRIPTION
**Pull request by stsquared99**
/cc @drewbrokke @alee8888 @ChrisKian

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hey @stsquared99 

Is this error `com.liferay.portal.kernel.exception.NoSuchResourceActionException: com_liferay_my_account_web_portlet_MyAccountPortlet#ADD_TO_PAGE` relevant to your changes?

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:stop

**Pull request closed without merging**
