### PR TITLE
LPS-122414 Number of accounts for Account Groups do not reflect in list view

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LPS-122414

@drewbrokke @jonmak08

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:foward

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez the failure seems unrelated. can we re-run?

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
