### PR TITLE
LPS-118619 Display custom fields when editing an account

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LPS-118619

@drewbrokke

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by alee8888** [comment]
ci:reevaluate:1197401_7893

**Comment by pei-jung** [comment]
ci:reevaluate:1197401_7893

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
