### PR TITLE
LPS-115250 Manually add Account Groups

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez, @Sharryxue is this a real test failure?

**Comment by Sharryxue** [comment]
Hello @pei-jung 
The failed functional test seems more like a flaky issue, the chrome not reachable for some reason, will retrigger the forward test, and keep tracking the issue.
/cc @patriciajeanperez

**Comment by Sharryxue** [comment]
ci:forward

**Comment by pei-jung** [comment]
Thanks @Sharryxue!

**Pull request closed without merging**
